@startuml
title My Tickets - User

actor User
control ":TicketSystem" as UD
participant ":TicketService" as TS
entity "ticket:TicketRecord" as ticket

== 1. User navigates to "My Tickets" section ==
User -> UD : viewPurchasedTickets(userId)
activate UD
UD -> TS : hasPurchasedTickets()
activate TS
TS --> UD : return true
deactivate TS
UD -> TS : getPurchasedTickets(userId)
activate TS
TS --> UD : return PurchasedTicketsList
deactivate TS
UD -> UD : displayTicketsList()
UD --> User :
deactivate UD
== 2. System displays a list of purchased tickets ==
@enduml
