@startuml
title Update Event - 01 Basic Course of Events

actor "Organiser/Administrator" as OA
control EventSystem as System
participant ":EventService" as Service
entity "selected : Event" as Event

== 1. The organiser/administrator selects the relevant event from the display to be updated **(01 - List Events Page - Organiser)** **(02 - List Events Page - Administrator) ==
note right of OA: This part happens in Javascript

== 2. The system displays a dialog to enter the event details **(07 - Update Event Page)**\n3. The organiser/administrator updates the details of the event and clicks "Save" ==

OA -> System: updateEvent(details)
activate System

System -> Service: updateEvent(details)
activate Service

Service -> Event: Event.setDetails(details)

Service -> Service: updatedEvent(Event)
note over Service: The saveUpdatedEvent method represents\nsaving the updated event to the database
Service --> Service:
Service --> System: event saved
deactivate Service

System -> Service: events := listAllEvents()
System -> System: updateDisplay()

System --> OA
deactivate System

== 4. The system updates the view to show the current events for the specified organiser/administrator, including the newly changed event **(01 - List Events Page - Organiser)** **(02 - List Events Page - Administrator) ==
@enduml
