@startuml
title View Venue Details - Organizer/Administrator

actor Organizer_and_Administrator as OrganizerAdmin
control ":VenueSystem" as VMS
participant ":VenueService" as VMSS
entity "venue:Venue" as DB

== 1. The user selects "Detail" on Manage Venue Page ==
OrganizerAdmin -> VMS : selectVenueDetail(venueId)
activate VMS

VMS -> VMSS : getVenueDetails(venueId)
activate VMSS
VMSS --> VMS : return VenueDetails
deactivate VMSS
VMS -> VMS : displayVenueDetails()
VMS --> OrganizerAdmin :
deactivate VMS
== 3. System displays the venue details to the user ==
@enduml
