@startuml
title Delete Event - 01 Basic Course of Events

actor Administrator as Admin
control "__: EventSystem__" as System
participant "__: EventService__" as Service
entity "__selected : Event__" as Event

== 1. The Administrator selects the remove events functionality of the event to be deleted **(02 - List Events Page - Administrator)** ==

Admin -> System: deleteEvent(Event)
activate System

System -> System: askForConfirmation()
System -> Admin: confirm()
activate Admin
== 2. The system asks the Administrator to confirm **(04 - Delete Events - Confirmation Dialog)** \n3. The Administrator selects **Yes** ==
Admin --> System: return true
deactivate Admin

System -> Service: deleteEvent(Event)
activate Service
note over Service: The deleteEvent method is a standin for\nthe future operation of deleting the selected\nevent object from the database
Service -> Event: <<destroy>>
destroy Event
deactivate Event
Service --> System
deactivate Service

System -> Service: getEvents()
Service --> System: return events
System -> System: displayEventList(events)

System --> Admin
deactivate System

== 4. The system updates the display to show the current events, with the selected event removed **(02 - List Events Page - Administrator)** ==
@enduml
