@startuml
title Delete Event - 02 Alternate Course of Events(Cancel)

actor Administrator as Admin
control EventSystem as System
participant ": EventService" as Service
entity "selected : Event" as Event

== 1. The Administrator selects the remove events functionality of the event to be deleted **(02 - List Events Page - Administrator)** ==

Admin -> System: deleteEvent(Event)
activate System

System -> System: askForConfirmation()
System -> Admin: confirm()
activate Admin
== 2. The system asks the Administrator to confirm **(04 - Remove Events - Confirmation Dialog)** \n3. The Administrator selects **No** ==
Admin --> System: return false
deactivate Admin


System --> Admin
deactivate System

== 4. The system returns to the List Events page of the application **(02 - List Events Page - Administrator)** ==
@enduml
